general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(0,0,0,1.0)
    blur_passes = 0
}

input-field {
    monitor =
    size = 280, 48
    position = 0, -120
    halign = center
    valign = center
    outline_thickness = 2
    inner_color = rgb(0,0,0)
    outer_color = rgb(139,0,0)
    font_color = rgb(255,255,255)
    placeholder_text =
    fail_text = $FAIL ($ATTEMPTS)
    fade_on_empty = false
    rounding = 0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%Y-%m-%d  %H:%M")"
    color = rgba(255,255,255,1.0)
    font_size = 36
    font_family = Hack
    position = 0, 80
    halign = center
    valign = center
}
