splash = false
ipc = on
preload = /home/groved/.wallpaper/we-exist-in-cyberspace.jpg
wallpaper = eDP-1,/home/groved/.wallpaper/we-exist-in-cyberspace.jpg
wallpaper = DP-3,/home/groved/.wallpaper/we-exist-in-cyberspace.jpg
wallpaper = DP-4,/home/groved/.wallpaper/we-exist-in-cyberspace.jpg
