function doc_create_clickable_icons(a,c,b,e){if(do_experimental_popupfill&&document.body){var f=check_nevers(document,g_nevers,document.location.href),d=c=a=!0,g=!0;null!=f&&(a=f.show_for_formfill,c=f.show_for_save,d=f.show_for_autofill,g=f.show_for_clickable_icon);verbose_log("g_popupfill_rows="+g_popupfill_rows+" show_clickable_for_autofill="+d+" show_clickable_for_save="+c+" show_clickable_for_formfill="+a);if((0<g_popupfill_rows&&d||0==g_popupfill_rows&&c||a)&&g){var f=document.getElementsByTagName("input"),
j,h={},m=checkDocumentForLoginOrphans(document),n=null;for(j=0;j<f.length;j++)if(e||popupfill_shoulddofield(document,f[j],b))try{var k=f[j],l=pickFormName(k.form),p=chk_form_has_password(document,k.form)||m,s=chk_form_is_nonlogin_form(document,k.form);if(e)if(looksLikeUsername(f[j]))p=!0,s=!1;else continue;var r=chk_form_ask_generate(document,k.form),u=!1;null!=n&&(null!=l&&l!=n)&&(u=!0,r=chk_form_ask_generate(document,k.form,u));var t=k.style.width.replace(/px/,"");if(""===t)try{t=("undefined"!=
typeof window.getComputedStyle?k.ownerDocument.defaultView.getComputedStyle(k,""):k.currentStyle).width.replace(/px/,"")}catch(w){}if(!(null!=h[l]&&1<=h[l]&&!isInputFieldPassword(document,k)&&(!p||r)&&!g_show_icon_only_on_focus))if((p&&(0<g_popupfill_rows&&d||0==g_popupfill_rows&&c)||(s&&!p||r)&&a)&&g)if((p||r)&&0<t&&30>t)verbose_log("skipping loginform icon create on "+LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because field is too thin");else if(s&&0<t&&100>t)verbose_log("skipping nonloginform icon create on "+
LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because field is too thin");else if(s&&is_search_field(document,k,!0))verbose_log("skipping nonloginform icon create on "+LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because it looks like a search field");else if(s&&k.readOnly)verbose_log("skipping nonloginform icon create on "+LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME)+"because it is read-only");else{var q;p&&!r?(n=l,g_isie?ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",
formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(q="sites")):p&&r?g_aspx_hack&&g_found_aspx?(g_isie?ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(q="sites")):(verbose_log("CONFLICT: form "+l+" is a signup form and login form; treat as a signup form and present formfill options"),g_isie?ie_setpopupfillhint({formid:l,rowtype:"formfills"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&
(q=isInputFieldPassword(document,k)?"generate":"formfills")):!p&&r&&chk_form_changepw(document,k.form)?(g_isie?ie_setpopupfillhint({formid:l,rowtype:"sites"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(q="sites")):(g_isie?ie_setpopupfillhint({formid:l,rowtype:"formfills"}):sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&(q="formfills"));if(checkIsDisplayed(document,k,0)){g_do_icon_number_hint?create_or_move_overlay_icon(document,
LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME),OK_CREATE,q,g_icon_numbers):create_or_move_overlay_icon(document,LP_getname(k,LP_GETNAME_FAVOR_ID_OVER_NAME),OK_CREATE);g_save_suggest_msg&&(q&&null!=typeof g_icon_numbers&&null!=typeof g_icon_numbers.sites&&1>g_icon_numbers.sites)&&addEventHandler(k,"click",function(a){var b=getEventTarget(a);setTimeout(function(){do_save_suggest_msg(b,document)},0);stopEventPropagation(a);return!1},!1);if(g_clickable_input&&(!("password"==k.type&&formHasUsernameField(k))||
g_clickable_input_on_password)&&"true"!==k.getAttribute("clickev")&&"sites"==q)k.setAttribute("clickev","true"),addEventHandler(k,"click",function(a){a=getEventTarget(a);var b=MAGIC+LP_getname(a,LP_GETNAME_FAVOR_ID_OVER_NAME);null!=document.getElementById(b)&&(g_clickable_input_on_password?is_your_popup_showing(document)||conditional_create_popup(document,a,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(document,k.form),popupfilltoggle(document,b,a,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)));
return!1},!1);null==h[l]?h[l]=1:h[l]++}}}catch(v){verbose&&alert("error: "+v.message+" stack: "+v.stack)}!1==g_weaseled&&setTimeout(function(){weasel(100)},500);g_weaseled=!0}}}
function popupfilltoggle(a,c,b,e,f,d){if(do_experimental_popupfill)if(null==g_port&&g_ischrome)console_log("disconnected from BG, abort");else{var g=d?!0:!1;g_save_suggest_msg&&setTimeout(function(){destroy_save_suggest_msg(a,MSGDIVID,null);return!1},0);g_keyboardNav=!1;var j;d=b.type;var h=LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(g_clickable_input)if(g_clickable_input_on_password){j=g_popup_active_username;var m=g_popup_active_password;null==j&&(j="undefined"==typeof b.form||null==b.form?doc_get_orphan_username(a):
form_get_username(a,b.form));null==m&&(m="undefined"==typeof b.form||null==b.form?doc_get_orphan_password(a):form_get_password(a,b.form));j&&m?(j=j.value,verbose_log("PASS3 username="+j),null!=j&&0<j.length&&!g_isie&&sendBG({cmd:"popupfillinputsave",inputstr:j,inputid:h,inputtype:d})):(verbose_log("PASS2 pass empty string"),g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:h,inputtype:d}))}else j=b.value,null!=j&&0<j.length&&(verbose_log("PASS1 pass parent field string "+j),g_isie||sendBG({cmd:"popupfillinputsave",
inputstr:j,inputid:h,inputtype:d}));else j="",g_isie||(sendBG({cmd:"popupfillinputsave",inputstr:j,inputid:h,inputtype:d}),verbose_log("PASS0 pass empty string"));d=a.getElementById(c);h=a.getElementById(MAGICIFRAME+c);if(null==h){g_popupfill_ctr>=g_popupfill_max&&(closepopupfills(a),g_popupfill_ctr=0);g_popupfill_ctr=1;g_popupfill_parent_last=g_popupfill_parent=b;verbose_log("["+g_docnum+"]: popupfilltoggle() set: g_popupfill_parent_last="+g_popupfill_parent_last);g_isie?(h=pickFormName(b.form),
j=ie_getpopupfillhint(h),null==j&&(j="sites"),g={rowtype:j,offergenerate:e?"1":"0",formid:h,fieldid:LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME),fieldtype:b.type,opentosave:g},g=LPJSON.stringify(g),document.documentElement.setAttribute("lpifmsg",g)):(h=pickFormName(b.form),e=e?1:0,sendBG({cmd:"setpopupfilllastactive",active:h,activefieldid:LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME),ask_generate:e,opentosave:g,activefieldtype:b.type}));g=chk_form_is_nonlogin_form(document,b.form);h=checkDocumentForLoginOrphans(document);
h=chk_form_has_password(document,b.form)||h;b=g_popupfill_rows;g&&!h&&(b=g_popupfill_rows_FF);g=g_popupfill_widest+40;120>g&&(g=120);g<g_popupfill_parent.offsetWidth&&(g=g_popupfill_parent.offsetWidth,g+=2*Math.abs(POPUP_FIELD_OFFSET));if(1==b&&!create_onerow_iframe){h=null;g_fillaid&&(h=g_fillaid);isEmptyObject(g_autofillsites)||(h=g_autofillsites[0].aid);if(null!=h){sendBG({cmd:"autofillaid",aid:h});verbose_log("filling only, not creating 1 row iframe");return}verbose_log("tried to fill form with invalid acct")}0==
b&&!do_popup_actions||0==b&&f==NO_FORCE_NOHITS?verbose_log("not creating empty iframe"):(h="undefined"!=typeof g_isloggedin?g_isloggedin:lploggedin,g_dologin_clickable&&!h&&(!g_isie||g_isie&&f==FORCE_SHOW_NOHITS_NOLOGIN)?(verbose_log("login state: checking whether to issue Chrome login prompt"),f!=FORCE_SHOW_NOHITS_NOLOGIN&&(g_isie||sendBG({cmd:"dologinaction"}))):(g_isie||sendBG({cmd:"popupregister",docnum:g_docnum}),h=calculate_iframe_pos(a,d,g),null!=h?(f=h.posx,h=h.posy,10<b&&(b=10),e&&(b=10),
do_popup_actions&&(b+=2),popupfill_create_iframe(a,f,h,c,b,g,g_minheight_override),g_popupfill_iframe_width_save=g):g_popupfill_ctr=0,g_use_grey_icons&&change_clickable_icon_to_cancel(a,d.id)))}else h.parentNode.removeChild(h),g_popupfill_parent_last=g_popupfill_parent,g_popupfill_parent=null,g_popupfill_ctr=0,verbose_log("["+g_docnum+"]: popupfilltoggle() set: g_popupfill_parent_last="+g_popupfill_parent_last)}}
function popupfill_create_iframe(a,c,b,e,f,d,g){if(do_experimental_popupfill){c=parseInt(c)+"px";b=parseInt(b)+"px";var j=a.body;a=a.createElement("iframe");a.id=MAGICIFRAME+e;a.name=MAGICIFRAME+e;a.src=g_isie?"https://.0..lastpass.com/#framesrc=LPMAGIC":urlprefix+"popupfilltab.html";0>parseInt(c)&&(c="0px");0>parseInt(b)&&(b="0px");g_frame_css_str="position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5);";
a.style.cssText=g_frame_css_str;j.appendChild(a);a.width=parseInt(d)+"px";a.height="26px";"undefined"!=typeof f&&0<f&&(a.height=24*f+23+"px");a.height=0<parseInt(g)?parseInt(g)+"px":parseInt(a.height)+"px";e=parseInt(a.width)+"px";f=parseInt(a.height)+"px";a.style.cssText=g_frame_css_str+("width: "+e+" !important; height: "+f+" !important; top:"+b+" !important; left:"+c+" !important; ")}}
function weasel(a){g_ctr_weasel++;if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;popupfill_resize();g_weasel_id=setTimeout(function(){weasel(a)},a)}}function end_weasel(){do_experimental_popupfill&&null!=g_weasel_id&&(clearTimeout(g_weasel_id),g_weasel_id=null,verbose_log("clearTimeout weasel"),g_weaseled=!1)}
function handle_form_text_change(a,c,b,e){if(do_experimental_popupfill&&!(null==b||null==c||null==e||null==e.keyCode)&&"lpwebsiteeventform"!=b.name&&"lpmanualform"!=b.name&&popupfill_shoulddofield(a,c,SHOULD_DO_ALWAYS)){e=c.value;var f=LP_getname(c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(g_clickable_input_on_password){var d=g_popup_active_username,g=g_popup_active_password;null==d&&(d="undefined"==typeof c.form||null==c.form?doc_get_orphan_username(a):form_get_username(a,c.form));null==g&&(g="undefined"==
typeof c.form||null==c.form?doc_get_orphan_password(a):form_get_password(a,c.form));a=checkDocumentForLoginOrphans(document);a=chk_form_has_password(document,b)||a;var j=chk_form_is_nonlogin_form(document,b),h=chk_form_ask_generate(document,b);if(d&&g&&(a||h)&&!j){if(c!=d){c==g?(g_isie||(e=d.value,sendBG({cmd:"popupfillinputsave",inputstr:e,inputid:f,inputtype:"password"})),verbose_log("KEYPASS4 username="+e)):(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log('KEYPASS5 username=""'));
return}}else{g_isie||(sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log('KEYPASS6 formfill? username=""'));return}}if(null==e||0==e.length)g_isie||sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f}),verbose_log("KEYPASS7 empty username");else if(!(0>=getcount(g_autofillsites))||g_change_icon_on_input){var d=0,g=null,m;for(m in g_autofillsites)0==g_autofillsites[m].useusername.indexOf(e)&&(d++,g=g_autofillsites[m]);if(1==d)do_autofill_if_matched?g_isie||sendBG({cmd:"autofillaid",
aid:g.aid}):(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:e,inputid:f,inputtype:c.type,issaveall:issaveall(b)}),verbose_log("KEYPASS8 match>0 username="+e));else if(g_isie||sendBG({cmd:"popupfillinputsave",inputstr:e,inputid:f,inputtype:c.type,issaveall:issaveall(b)}),verbose_log("KEYPASS9 match>1 username="+e),chk_form_has_password(document,b),g_change_icon_on_input&&(c=b.elements,null!=c))for(b=0;b<c.length&&!(m=c[b],checkIsDisplayed(document,m,0)&&isInputFieldPassword(document,m)&&null!=m.value&&
0<m.value.length);b++);}}}function issaveall(a){a=a.elements;for(var c=0,b=0,e=0,f=0;f<a.length;f++){var d=a[f].type;"password"==d?b++:"text"==d||"tel"==d||"email"==d?c++:"textarea"==d&&e++}return 1==c&&1==b&&0==e?!1:!0}
function relocate_popupfill_iframes(a){if(do_experimental_popupfill){var c,b=null,e=a.getElementsByTagName("iframe");for(c=0;c<e.length;c++){var f=e[c],b=null;if("undefined"!=typeof f.id&&null!=f.id){var d=MAGICIFRAME;if(0==f.id.indexOf(d))if(d=f.id.substr(d.length),d=a.getElementById(d),null!=d){var g=calculate_iframe_pos(a,d,0<g_minwidth_override?g_minwidth_override:0);if(null!=g){var d=g.posx,j=g.posy,g=parseInt(d)+"px",h=parseInt(j)+"px",m=0;if(0<parseInt(g_minwidth_override)){var m=Math.max(parseInt(g_popupfill_iframe_width_save),
parseInt(g_minwidth_override))+"px",n=getWindowWidth(window);parseInt(m)+parseInt(g)>n&&(g=n-parseInt(m)-20+"px")}else 0<parseInt(g_popupfill_iframe_width_save)?m=parseInt(g_popupfill_iframe_width_save)+"px":(null==b&&(b="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(f):f.currentStyle),m=b.width);0>parseInt(g)&&(g="0px");n=0;0<parseInt(g_minheight_override)?n=Math.max(parseInt(g_popupfill_iframe_height_save),parseInt(g_minheight_override))+"px":0<parseInt(g_popupfill_iframe_height_save)?
n=parseInt(g_popupfill_iframe_height_save)+"px":(null==b&&(b="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(f):f.currentStyle),n=b.height);if(g_iframe_scroll_hack&&!g_frame_scrollable_set){var b=parseInt(n),k=parseInt(m),l;l="undefined"!=typeof window.getComputedStyle?window.getComputedStyle(a.body):"undefined"!=typeof a.documentElement?a.documentElement.currentStyle:a.body.currentStyle;parseInt(l.height);parseInt(l.width);l=window.innerHeight;var p=window.innerWidth;if(null!=
b&&0<b&&null!=l&&0<l||null!=k&&0<k&&null!=p&&0<p)if(parseInt(j)+b>l||parseInt(d)+k>p){d=!1;try{window.self!=window.top&&(d=!0)}catch(s){d=!0}d&&(g_isie||(verbose_log("ensuring this frame/iframe has scrolling enabled"),sendBG({cmd:"iframescrollenable",href:a.location.href})),g_frame_scrollable_set=!0)}}f.style.cssText=g_frame_css_str+("width: "+m+" !important; height: "+n+" !important; top:"+h+" !important; left:"+g+" !important; position: absolute;")}}else closepopupfills(a)}}}}var KEY_ESCAPE=27;
function keypress_handler(a){a.keyCode==KEY_ESCAPE&&closepopupfills(document);return!1}var KEY_TAB=9,KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,KEY_SHIFT=16,KEY_RIGHT=39,KEY_PAGEDOWN=34,KEY_PAGEUP=33,KEY_END=35,KEY_HOME=36;
function field_keypress_handler(a,c){var b=a.keyCode;if(b==KEY_ESCAPE)closepopupfills(document);else if(b==KEY_TAB)closepopupfills(document);else if(b==KEY_DOWN){if(!is_your_popup_showing(document)){var e=document,f=MAGIC+LP_getname(c,LP_GETNAME_FAVOR_ID_OVER_NAME);set_active_username_password(document,c.form);popupfilltoggle(e,f,c,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)}}else if(b!=KEY_UP&&!(b==KEY_SHIFT||0==b)&&!(b==KEY_RIGHT&&a.altKey)&&!is_modifier_key(b)&&b!=KEY_ENTER){if(g_ischrome&&g_setup_hotkey_handler){if(is_hotkey_event(a))return}else if(g_isie&&
(e=""+(a.ctrlKey?"control ":""),e+=a.metaKey?"meta ":"",e+=a.altKey?"alt ":"",e+=a.shiftKey?"shift ":"",verbose_log("keycode == "+b+" "+e),"undefined"!=typeof a.metaKey&&a.metaKey||"undefined"!=typeof a.altKey&&a.altKey||"undefined"!=typeof a.ctrlKey&&a.ctrlKey))return;if("password"==c.type&&formHasUsernameField(c))if(g_clickable_input_on_password)!is_your_popup_showing(document)&&!chk_form_ask_generate(document,c.form)&&conditional_create_popup(document,c,FORCE_SHOW_NOHITS_NOLOGIN);else return;if(!chk_form_has_password(document,
c.form))return;is_your_popup_showing(document)||(g_clickable_input_on_password?(f=MAGIC+LP_getname(c,LP_GETNAME_FAVOR_ID_OVER_NAME),e=LP_getElementByIdOrName(document,f).getAttribute("intrinsic"),null!=e&&"sites"==e&&conditional_create_popup(document,c,FORCE_SHOW_NOHITS_NOLOGIN)):(e=document,f=MAGIC+LP_getname(c,LP_GETNAME_FAVOR_ID_OVER_NAME),popupfilltoggle(e,f,c,NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)),g_keyboardNav=!0)}is_your_popup_showing(document)&&(b==KEY_UP&&(g_isie||(sendBG({cmd:"popupfillinputfocusdecrement",
count:1}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_DOWN&&(g_extended_kbd_nav&&a.altKey&&g_hide_navbar?is_your_popup_showing(document)&&(g_isie||sendBG({cmd:"popupfillinputshownavbar"})):g_isie||(sendBG({cmd:"popupfillinputfocusincrement",count:1}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_ENTER&&(g_popupfill_parent==c&&g_keyboardNav)&&(g_isie||sendBG({cmd:"popupfillinputfocuschoose"}),
g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_PAGEUP&&(g_isie||(sendBG({cmd:"popupfillinputfocusdecrement",count:12}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),stopEventPropagation(a)),b==KEY_PAGEDOWN&&(g_isie||(sendBG({cmd:"popupfillinputfocusincrement",count:12}),g_keyboardNav=!0),stopEventPropagation(a)),b==KEY_END&&!g_isie&&(sendBG({cmd:"popupfillinputfocusincrement",count:1073741824}),g_keyboardNav=!0),b==KEY_HOME&&!g_isie&&
(sendBG({cmd:"popupfillinputfocusdecrement",count:1073741824}),g_keyboardNav=!0));return!1}
function relocate_popupfill_clickables(a){try{var c,b=0;for(c in g_popup_divs)if(g_popup_divs.hasOwnProperty(c)){var e=g_popup_divs[c].substr(MAGIC.length);if(null!=e&&0<e.length){var f=e;if(null==LP_getElementByIdOrName(a,f)&&!g_double_password_hack&&!g_double_secret_password_hack){var d=a.getElementById(g_popup_divs[c]);if(g_do_icon_number_hint)var g=a.getElementById(g_popup_divs[c]+"_numspan");null!=d&&(d.parentNode.removeChild(d),verbose_log("relocate: deleting orphaned icon container for "+e),
b++);g_do_icon_number_hint&&null!=g&&(g.parentNode.removeChild(g),verbose_log("relocate: deleting orphaned icon number for "+e),b++);delete g_popup_divs[c]}else if(g_do_icon_number_hint){if(d=a.getElementById(g_popup_divs[c]),null!=d){var j=d.getAttribute("intrinsic");null!=j&&("sites"!=j&&"formfills"!=j)&&(j=null);var h={};h.sites=0<g_icon_number_overrides.sites?g_icon_number_overrides.sites:g_icon_numbers.sites;h.formfills=0<g_icon_number_overrides.formfills?g_icon_number_overrides.formfills:g_icon_numbers.formfills;
create_or_move_overlay_icon(a,f,NO_CREATE,j,h)}}else create_or_move_overlay_icon(a,f,NO_CREATE)}}0<b&&setTimeout(function(){checkShouldRecheck()},500)}catch(m){verbose_log("relocate_popupfill_clickables caught error:"+m.message)}}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,c,b){if(!do_experimental_popupfill||null==c)return null;var e=c.style.left,f=c.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(e)||0>parseInt(f)){var d=a.getElementById(MAGICIFRAME+c.id);if(null!=d)return b=getAbsolutePos(a,d),f=parseInt(b.top)+"px",e=parseInt(b.left)+"px",{posx:e,posy:f}}d=c.id.substr(MAGIC.length);d=LP_getElementByIdOrName(a,d);if(null!=d){d=getAbsolutePos(a,d);null!=d&&(e=parseInt(d.left)+POPUP_FIELD_OFFSET+"px",f=
parseInt(d.top)+parseInt(d.height)+"px",g_do_icon_number_hint&&(f=parseInt(d.top)+parseInt(d.height)+4+"px"));if(null==b||0==b)d=a.getElementById(MAGICIFRAME+c.id),null!=d&&(b=getAbsolutePos(a,d).width);a=getWindowWidth(window);parseInt(b)+parseInt(e)>a&&(e=a-parseInt(b)-20+"px")}e=parseInt(e)+"px";f=parseInt(f)+"px";return{posx:e,posy:f}}function verbose_log(a){verbose&&console_log(a)}function is_watermark(){return!1}function checkAskGenerate(){}
function sendKey(a,c){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(c,0,KeyEvent[keyName],!1)}catch(b){lpdbg("error",b)}return null}
function send_simulated_key(a,c,b,e){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;c=a.ownerDocument.createEvent("KeyboardEvent");c.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,e,!1,b,b);var f=a.dispatchEvent(c);c=a.ownerDocument.createEvent("KeyboardEvent");c.initKeyboardEvent("keyup",!0,!0,null,!1,!1,e,!1,b,b);a.dispatchEvent(c);return f}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_CANCEL:3,DOM_VK_HELP:6,DOM_VK_BACK_SPACE:8,DOM_VK_TAB:9,DOM_VK_CLEAR:12,DOM_VK_RETURN:13,DOM_VK_ENTER:14,DOM_VK_SHIFT:16,DOM_VK_CONTROL:17,DOM_VK_ALT:18,DOM_VK_PAUSE:19,DOM_VK_CAPS_LOCK:20,DOM_VK_ESCAPE:27,DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_END:35,DOM_VK_HOME:36,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_PRINTSCREEN:44,DOM_VK_INSERT:45,DOM_VK_DELETE:46,DOM_VK_0:48,DOM_VK_1:49,DOM_VK_2:50,DOM_VK_3:51,
DOM_VK_4:52,DOM_VK_5:53,DOM_VK_6:54,DOM_VK_7:55,DOM_VK_8:56,DOM_VK_9:57,DOM_VK_SEMICOLON:59,DOM_VK_EQUALS:61,DOM_VK_A:65,DOM_VK_B:66,DOM_VK_C:67,DOM_VK_D:68,DOM_VK_E:69,DOM_VK_F:70,DOM_VK_G:71,DOM_VK_H:72,DOM_VK_I:73,DOM_VK_J:74,DOM_VK_K:75,DOM_VK_L:76,DOM_VK_M:77,DOM_VK_N:78,DOM_VK_O:79,DOM_VK_P:80,DOM_VK_Q:81,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_T:84,DOM_VK_U:85,DOM_VK_V:86,DOM_VK_W:87,DOM_VK_X:88,DOM_VK_Y:89,DOM_VK_Z:90,DOM_VK_WIN:91,DOM_VK_CONTEXT_MENU:93,DOM_VK_NUMPAD0:96,DOM_VK_NUMPAD1:97,DOM_VK_NUMPAD2:98,
DOM_VK_NUMPAD3:99,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD7:103,DOM_VK_NUMPAD8:104,DOM_VK_NUMPAD9:105,DOM_VK_MULTIPLY:106,DOM_VK_ADD:107,DOM_VK_SEPARATOR:108,DOM_VK_SUBTRACT:109,DOM_VK_DECIMAL:110,DOM_VK_DIVIDE:111,DOM_VK_F1:112,DOM_VK_F2:113,DOM_VK_F3:114,DOM_VK_F4:115,DOM_VK_F5:116,DOM_VK_F6:117,DOM_VK_F7:118,DOM_VK_F8:119,DOM_VK_F9:120,DOM_VK_F10:121,DOM_VK_F11:122,DOM_VK_F12:123,DOM_VK_F13:124,DOM_VK_F14:125,DOM_VK_F15:126,DOM_VK_F16:127,DOM_VK_F17:128,DOM_VK_F18:129,
DOM_VK_F19:130,DOM_VK_F20:131,DOM_VK_F21:132,DOM_VK_F22:133,DOM_VK_F23:134,DOM_VK_F24:135,DOM_VK_NUM_LOCK:144,DOM_VK_SCROLL_LOCK:145,DOM_VK_COMMA:188,DOM_VK_PERIOD:190,DOM_VK_SLASH:191,DOM_VK_BACK_QUOTE:192,DOM_VK_OPEN_BRACKET:219,DOM_VK_BACK_SLASH:220,DOM_VK_CLOSE_BRACKET:221,DOM_VK_QUOTE:222,DOM_VK_META:224};
function checkShouldRecheck(){if(do_experimental_popupfill&&(verbose_log("entered checkShouldRecheck()"),0<=g_input_cnt)){var a=countInputs(document);g_input_cnt!=a&&(formcachereset(document),g_isie?(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){sendBG({cmd:"recheckpage"})},200),g_input_cnt=a)}}function is_watermark_password(){return!1}
function addEventHandler(a,c,b){try{return null==a||null==c||null==b||0>=c.length?null:"undefined"!=typeof a.addEventListener?a.addEventListener(c,b,!1):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,b):null}catch(e){return verbose_log("addEventHandler failed, "+e.message),null}}
function stopEventPropagation(a){try{"undefined"!=typeof a.preventDefault?a.preventDefault():typeof window.event&&(window.event.returnValue=!1),"undefined"!=typeof a.stopPropagation?a.stopPropagation():typeof window.event&&(window.event.cancelBubble=!0)}catch(c){verbose_log("stopEventPropagation failed, "+c.message)}}function getEventTarget(a){a=a?a:window.event;if((a="undefined"!=typeof a.target?a.target:a.srcElement)&&"undefined"!=typeof a.nodeType&&3==a.nodeType)a=a.parentNode;return a};
