#!/bin/bash

set -euo pipefail
IFS=$'\n'

key="$1"
keyserver="${2:-keys.gnupg.net}"

check_code() {
  if [ "$?" -eq 1 ]; then
    rm $HOME/.gnupg/ || true
    mv $HOME/.gnupg.old/ $HOME/.gnupg/
  fi
}

echo "Killing GPG Agent..."
killall -9 gpg-agent || true
systemctl stop --user gpg-agent.service
systemctl stop --user gpg-agent.socket
systemctl stop --user gpg-agent-ssh.socket
systemctl stop --user gpg-agent-browser.socket
systemctl stop --user gpg-agent-extra.socket

echo "Removing Sockets..."
rm -rf /run/user/1000/gnupg/

echo "Rotating gnupg home folder..."
if [ -d "$HOME/.gnupg.old" ]; then
  rm -rf $HOME/.gnupg.old
fi
mv $HOME/.gnupg/ $HOME/.gnupg.old/

# Only trap after this is run to recover on a pull key failure and not lose
# configurations
trap 'check_code' EXIT

echo "Pulling Key..."
gpg --keyserver $keyserver --recv-key $key

echo "Updating owner trust..."
echo "$key":6: | gpg --import-ownertrust

echo "Moving gpg configs back..."
cp $HOME/.gnupg.old/gpg-agent.conf $HOME/.gnupg/
cp $HOME/.gnupg.old/gpg.conf $HOME/.gnupg/
cp $HOME/.gnupg.old/scdaemon.conf $HOME/.gnupg/
cp $HOME/.gnupg.old/sshcontrol $HOME/.gnupg/

echo "Restarting GPG Agent..."
systemctl start --user gpg-agent.service
gpg-connect-agent updatestartuptty /bye

echo "Unplug and re-plugin Yubikey then run 'gpg --card-status'"
