splash = false
ipc = on
preload = /home/groved/.wallpaper/edge-of-the-world-2k.jpg
wallpaper = DP-4,/home/groved/.wallpaper/edge-of-the-world-2k.jpg
wallpaper = DP-5,/home/groved/.wallpaper/edge-of-the-world-2k.jpg
wallpaper = DP-6,/home/groved/.wallpaper/edge-of-the-world-2k.jpg
wallpaper = HDMI-A-2,/home/groved/.wallpaper/edge-of-the-world-2k.jpg
