// Generated by CoffeeScript 1.6.1
(function() {
  var settings, syntaxtic;

  settings = false;

  chrome.extension.sendRequest({
    method: "getSettingsWithAction"
  }, function(response) {
    settings = response.settings;
    if (syntaxtic.windowLoaded) {
      console.log('Loaded');
      return syntaxtic.doHighlight();
    } else {
      console.log('Issuing onload');
      return window.onload = function() {
        syntaxtic.windowLoaded = true;
        return syntaxtic.doHighlight();
      };
    }
  });

  syntaxtic = {
    windowLoaded: false,
    doHighlight: function() {
      var applyPageSpecificSettings, beautifyCsv, changeFontSize, checkForObjectiveC, hasHtmlContentType, highlight, loadScript;
      if (!settings) {
        return;
      }
      hasHtmlContentType = function() {
        var content, httpEquiv, metaTags, result, tag, _i, _len;
        console.log('has html content?');
        result = false;
        metaTags = document.getElementsByTagName('meta');
        console.log('Meta Tags:', metaTags);
        for (_i = 0, _len = metaTags.length; _i < _len; _i++) {
          tag = metaTags[_i];
          console.log('Tag:', tag, metaTags[tag]);
          httpEquiv = tag.httpEquiv;
          content = tag.content;
          if (httpEquiv === 'undefined') {
            continue;
          }
          if (httpEquiv.toLowerCase() === "content-type" && content.toLowerCase().match("html")) {
            result = true;
            break;
          }
        }
        return result;
      };
      highlight = function() {
        var css1, css2, css3;
        if (!document.body.innerHTML.match("003ew0hdafa1119dadfa39aje")) {
          if (document.body.firstChild !== null && document.getElementsByTagName('pre')[0] === document.body.firstChild) {
            document.body.innerHTML = "<!-- 003ew0hdafa1119dadfa39aje -->\n<script type=\"syntaxhighlighter\" class=\"brush: " + window.brushAlias + "\">\n  <![CDATA[" + document.body.firstChild.innerHTML + "]]>\n</script>";
          }
          css1 = document.createElement("link");
          css1.href = chrome.extension.getURL("styles/shCore.css");
          css1.type = "text/css";
          css1.rel = "stylesheet";
          document.head.appendChild(css1);
          css2 = document.createElement("link");
          css2.href = chrome.extension.getURL("styles/" + settings.theme);
          css2.type = "text/css";
          css2.rel = "stylesheet";
          document.head.appendChild(css2);
          css3 = document.createElement("style");
          css3.appendChild(document.createTextNode(".toolbar {display:none}"));
          document.head.appendChild(css3);
          return SyntaxHighlighter.highlight();
        }
      };
      beautifyCsv = function() {
        var csvArray, csvArrayDecoded, firstDimension, i, j, k, l, m, maxColLengthsHash, newCsvData, orig, secondDimension, strData, strDecode, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _n, _o, _ref, _ref1, _ref2, _results, _results1;
        strData = document.body.firstChild.innerHTML;
        csvArray = CsvToArray(strData, ",");
        maxColLengthsHash = (function() {
          _results = [];
          for (var _i = 1, _ref = csvArray[0].length; 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
          return _results;
        }).apply(this).map(function(i) {
          return -1;
        });
        csvArrayDecoded = (function() {
          _results1 = [];
          for (var _j = 1, _ref1 = csvArray.length; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; 1 <= _ref1 ? _j++ : _j--){ _results1.push(_j); }
          return _results1;
        }).apply(this).map(function(i) {
          return [];
        });
        for (i = _k = 0, _len = csvArray.length; _k < _len; i = ++_k) {
          firstDimension = csvArray[i];
          for (j = _l = 0, _len1 = firstDimension.length; _l < _len1; j = ++_l) {
            orig = firstDimension[j];
            strDecode = html_entity_decode(orig);
            csvArrayDecoded[i][j] = strDecode;
            if (strDecode.length > maxColLengthsHash[j]) {
              maxColLengthsHash[j] = strDecode.length;
            }
          }
        }
        newCsvData = "";
        for (k = _m = 0, _len2 = csvArray.length; _m < _len2; k = ++_m) {
          firstDimension = csvArray[k];
          for (l = _n = 0, _len3 = firstDimension.length; _n < _len3; l = ++_n) {
            secondDimension = firstDimension[l];
            for (m = _o = 0, _ref2 = maxColLengthsHash[l] - csvArrayDecoded[k][l].length; 0 <= _ref2 ? _o <= _ref2 : _o >= _ref2; m = 0 <= _ref2 ? ++_o : --_o) {
              newCsvData += " ";
            }
            newCsvData += secondDimension;
            if (l + 1 === firstDimension.length) {
              newCsvData += '\n';
            } else {
              newCsvData += ", ";
            }
          }
        }
        document.body.firstChild.innerHTML = newCsvData;
        return window.brushAlias = "plain";
      };
      checkForObjectiveC = function() {
        var strData;
        strData = document.body.innerHTML;
        if (strData.match(/(@interface|@protocol|@INTERFACE|@PROTOCOL)/) != null) {
          return "objc";
        } else {
          return "cpp";
        }
      };
      changeFontSize = function() {
        var newNode, styleElement;
        styleElement = document.createElement('style');
        styleElement.type = 'text/css';
        styleElement.id = 'fontOverride';
        document.getElementsByTagName('head')[0].appendChild(styleElement);
        newNode = document.createTextNode(".syntaxhighlighter, .syntaxhighlighter code, .syntaxhighlighter div {\n        font-size: " + settings.fontSize + " !important;\n        font-family: '" + settings.fontFamily + "' !important;\n      }");
        return styleElement.appendChild(newNode);
      };
      applyPageSpecificSettings = function() {
        if (settings.gutterBlacklist.indexOf(document.location.href) > -1) {
          loadScript(chrome.extension.getURL("toggle_gutter.js"));
        }
        if (settings.highlightBlacklist.indexOf(document.location.href) > -1) {
          return loadScript(chrome.extension.getURL("toggle_highlight.js"));
        }
      };
      loadScript = function(url, callback) {
        var head, script;
        head = document.getElementsByTagName('head')[0];
        script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = url;
        script.onreadystatechange = callback;
        script.onload = callback;
        return head.appendChild(script);
      };
      console.log('Main');
      if ((window.brushAlias != null) && window.brushAlias !== "" && !hasHtmlContentType()) {
        if (window.brushAlias === 'csv') {
          beautifyCsv();
        }
        if (window.brushAlias === 'cHeader') {
          window.brushAlias = checkForObjectiveC();
        }
        highlight();
        changeFontSize();
        return applyPageSpecificSettings();
      }
    }
  };

  window.onload = function() {
    return syntaxtic.windowLoaded = true;
  };

}).call(this);
