// Generated by CoffeeScript 1.6.1
(function() {
  var toggle_element;

  toggle_element = function(class_name) {
    var element;
    element = document.getElementsByClassName(class_name)[0];
    if (element != null) {
      if (element.style.display === '') {
        return element.style.display = 'none';
      } else {
        return element.style.display = '';
      }
    }
  };

  toggle_element('gutter');

}).call(this);
