// Generated by CoffeeScript 1.6.1
(function() {
  var toggle_hilight;

  toggle_hilight = function() {
    var stylesheet, _i, _len, _ref, _results;
    _ref = document.styleSheets;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      stylesheet = _ref[_i];
      if (stylesheet.href && stylesheet.href.match(/.*shTheme[a-zA-Z]*\.css/)) {
        _results.push(stylesheet.disabled = !stylesheet.disabled);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  toggle_hilight();

}).call(this);
