/*
 AngularJS v1.0.9-3ccec13
 (c) 2010-2012 Google, Inc. http://angularjs.org
 License: MIT
*/
(function(m,h,n){'use strict';function k(a){var d={};a=a.split(",");var b;for(b=0;b<a.length;b++)d[a[b]]=!0;return d}function D(a,d){function b(a,b,c,g){b=h.lowercase(b);if(r[b])for(;f.last()&&s[f.last()];)e("",f.last());t[b]&&f.last()==b&&e("",b);(g=u[b]||!!g)||f.push(b);var l={};c.replace(E,function(a,b,d,e,c){l[b]=p(d||e||c||"")});d.start&&d.start(b,l,g)}function e(a,b){var e=0,c;if(b=h.lowercase(b))for(e=f.length-1;0<=e&&f[e]!=b;e--);if(0<=e){for(c=f.length-1;c>=e;c--)d.end&&d.end(f[c]);f.length=
e}}var c,g,f=[],l=a;for(f.last=function(){return f[f.length-1]};a;){g=!0;if(f.last()&&v[f.last()])a=a.replace(RegExp("(.*)<\\s*\\/\\s*"+f.last()+"[^>]*>","i"),function(a,b){b=b.replace(F,"$1").replace(G,"$1");d.chars&&d.chars(p(b));return""}),e("",f.last());else{if(0===a.indexOf("\x3c!--"))c=a.indexOf("--\x3e"),0<=c&&(d.comment&&d.comment(a.substring(4,c)),a=a.substring(c+3),g=!1);else if(w.test(a)){if(c=a.match(w))a=a.replace(c[0],""),g=!1}else if(H.test(a)){if(c=a.match(x))a=a.substring(c[0].length),
c[0].replace(x,e),g=!1}else I.test(a)&&(c=a.match(y))&&(a=a.substring(c[0].length),c[0].replace(y,b),g=!1);g&&(c=a.indexOf("<"),g=0>c?a:a.substring(0,c),a=0>c?"":a.substring(c),d.chars&&d.chars(p(g)))}if(a==l)throw"Parse Error: "+a;l=a}e()}function p(a){q.innerHTML=a.replace(/</g,"&lt;");return q.innerText||q.textContent||""}function z(a){return a.replace(/&/g,"&amp;").replace(J,function(a){return"&#"+a.charCodeAt(0)+";"}).replace(/</g,"&lt;").replace(/>/g,"&gt;")}function A(a){var d=!1,b=h.bind(a,
a.push);return{start:function(a,c,g){a=h.lowercase(a);!d&&v[a]&&(d=a);d||!0!=B[a]||(b("<"),b(a),h.forEach(c,function(a,c){var e=h.lowercase(c);!0!=K[e]||!0===C[e]&&!a.match(L)||(b(" "),b(c),b('="'),b(z(a)),b('"'))}),b(g?"/>":">"))},end:function(a){a=h.lowercase(a);d||!0!=B[a]||(b("</"),b(a),b(">"));a==d&&(d=!1)},chars:function(a){d||b(z(a))}}}var y=/^<\s*([\w:-]+)((?:\s+[\w:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)\s*>/,x=/^<\s*\/\s*([\w:-]+)[^>]*>/,E=/([\w:-]+)(?:\s*=\s*(?:(?:"((?:[^"])*)")|(?:'((?:[^'])*)')|([^>\s]+)))?/g,
I=/^</,H=/^<\s*\//,F=/\x3c!--(.*?)--\x3e/g,w=/<!DOCTYPE([^>]*?)>/i,G=/<!\[CDATA\[(.*?)]]\x3e/g,L=/^((ftp|https?):\/\/|mailto:|#)/i,J=/([^\#-~| |!])/g,u=k("area,br,col,hr,img,wbr");m=k("colgroup,dd,dt,li,p,tbody,td,tfoot,th,thead,tr");n=k("rp,rt");var t=h.extend({},n,m),r=h.extend({},m,k("address,article,aside,blockquote,caption,center,del,dir,div,dl,figure,figcaption,footer,h1,h2,h3,h4,h5,h6,header,hgroup,hr,ins,map,menu,nav,ol,pre,script,section,table,ul")),s=h.extend({},n,k("a,abbr,acronym,b,bdi,bdo,big,br,cite,code,del,dfn,em,font,i,img,ins,kbd,label,map,mark,q,ruby,rp,rt,s,samp,small,span,strike,strong,sub,sup,time,tt,u,var")),
v=k("script,style"),B=h.extend({},u,r,s,t),C=k("background,cite,href,longdesc,src,usemap"),K=h.extend({},C,k("abbr,align,alt,axis,bgcolor,border,cellpadding,cellspacing,class,clear,color,cols,colspan,compact,coords,dir,face,headers,height,hreflang,hspace,ismap,lang,language,nohref,nowrap,rel,rev,rows,rowspan,rules,scope,scrolling,shape,span,start,summary,target,title,type,valign,value,vspace,width")),q=document.createElement("pre");h.module("ngSanitize",[]).value("$sanitize",function(a){var d=[];
D(a,A(d));return d.join("")});h.module("ngSanitize").directive("ngBindHtml",["$sanitize",function(a){return function(d,b,e){b.addClass("ng-binding").data("$binding",e.ngBindHtml);d.$watch(e.ngBindHtml,function(c){c=a(c);b.html(c||"")})}}]);h.module("ngSanitize").filter("linky",function(){var a=/((ftp|https?):\/\/|(mailto:)?[A-Za-z0-9._%+-]+@)\S*[^\s\.\;\,\(\)\{\}\<\>]/,d=/^mailto:/;return function(b){if(!b)return b;for(var e=b,c=[],g=A(c),f,h;b=e.match(a);)f=b[0],b[2]==b[3]&&(f="mailto:"+f),h=b.index,
g.chars(e.substr(0,h)),g.start("a",{href:f}),g.chars(b[0].replace(d,"")),g.end("a"),e=e.substring(h+b[0].length);g.chars(e);return c.join("")}})})(window,window.angular);

